### ISSUE TITLE
Layer Naming

### ISSUE THREAD

**Issue by mdaal** [demisjohn/ASML_JobCreator#42]
The code does not recognize that some non-alphanumeric characters are permissible in the layer name. Examples include "_" and "-".  A non-thorough fix is as follows:

Line 253 of exportlib.py is: 
if L.LayerID.isalnum():

Change this to: 
if L.LayerID.replace('_','').replace('-','').isalnum():

. . . for every permissible character

**Comment by demisjohn** [comment]
Also see this issue: https://github.com/demisjohn/ASML_JobCreator/issues/31 maybe same.

**Comment by fyodr** [comment]
See #31 for discussion.

**Comment by demisjohn** [comment]
@mdaal psing this issue because it is being discussed & fixed in #31 , utilizing your comments and code.
